# alembic/env.py

from logging.config import fileConfig  # Configure Alembic logging
import os  # Access environment variables
import sys  # Modify Python import path

from sqlalchemy import engine_from_config  # Create SQLAlchemy engine from Alembic config
from sqlalchemy import pool  # Provide connection pooling options

from alembic import context  # Alembic migration context

# Make the project root (/app) available to Python imports.
# This allows Alembic to import app.config and app.models.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.config import settings  # Load application configuration
from app.models import Base  # Load SQLAlchemy metadata for autogenerate


# Alembic Config object.
config = context.config

# Configure logging if alembic.ini contains logging configuration.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Tell Alembic which SQLAlchemy metadata belongs to our application.
# Autogenerate compares this metadata against the PostgreSQL database.
target_metadata = Base.metadata

# Use the database URL generated by app/config.py.
# This keeps the database configuration in one place.
config.set_main_option(
    "sqlalchemy.url",
    settings.database_url.replace("%", "%%"),
)


def run_migrations_offline() -> None:
    """
    Run migrations without creating a database connection.
    """

    url = config.get_main_option("sqlalchemy.url")

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations using a live PostgreSQL database connection.
    """

    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )

        with context.begin_transaction():
            context.run_migrations()


# Select offline or online migration mode.
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
